gcp_credentials = "./credentials/terraform-dev.key.json"
gcp_region = "us-east4"
gcp_zone = "us-east4-b"
gcp_project = "cldntventr"
cluster_dns = "cloudnativeentrepreneur.dev"
prod_cluster_dns = "cloudnativeentrepreneur.com"